### ISSUE TITLE
Warnings in log

### ISSUE THREAD

**Issue by pronebird** [pavelosipov/POSInputStreamLibrary#1]
Hello,

I use `POSInputStream` to stream ALAsset with AFNetworking. On each upload, I get a log message:

```
reject attempt to reopen stream.
```

Which is harmless but maybe you know what's the matter. I open stream before passing it to AFNetworking, otherwise I found that it won't work.

I'll look into tomorrow, but hope that you may be aware of this issue.

p.s.: probably I have to switch to `pos_inputStreamForCFNetworkWithAssetURL`, I suspect since that async open does not work properly with networking.

Cheers,
Andrej

**Comment by pavelosipov** [comment]
Good day, Andrej

I reject reopening because I have no idea what kind of behaviour should take place in that case. I treat reopening as a bug. A motivation is that If the 1st client is already streaming some asset and some other client at the same time decided to reopen the stream then the logic of the 1st client will be broken. When 1st will call read method next time he will assume that he will fetch next chunk of asset but not the 1st. 2nd client will assume he will read 1st chunk of the asset, because he just open it successfully.

I didn't test asset stream with AFNetworking, but I suppose that that frameworks uses CFNetwork in its underlaying layer. In that case you should use `pos_inputStreamForCFNetworkWithAssetURL` fabric method. That method enables a lot of workarounds in the stream object. What are they?
1. Open method will block calling thread. The reason is that opening asset stream take place in GUI thread and may take undefined amount of time. CFNetwork framework calls open in some worker thread and it assumes that stream will be ready for use just after open returns.
2. Stream will never move to error state, but you can be notified about error asynchronously via NSStreamDelegate. The reason is when stream moves to error state then CFNetwork framework tries to get error object via some plain C function. That function doesn't have correct bridge implementation and that crashes the app.

Feel free to ask any other questions if you have. I will be happy to know about results of your experiments with integration asset stream with AFNetworking library.

**Comment by pronebird** [comment]
Hi,

Thanks for your reply.

So I switched to CFNetwork initializer as you suggested:

``` objc
AFHTTPRequestOperation* operation = [manager POST:url parameters:parameters constructingBodyWithBlock:^(id<AFMultipartFormData> formData) {
            NSInputStream* inputStream = [NSInputStream pos_inputStreamForCFNetworkWithAssetURL:fileURL];

            [formData appendPartWithInputStream:inputStream
                                           name:name
                                       fileName:uploadFileName
                                         length:asset.defaultRepresentation.size
                                       mimeType:@"application/octet-stream"];

        } ... ]
```

And now I get assertion:

```
2014-12-09 13:58:18.059 HelloWorld[1634:631286] *** Assertion failure in -[POSBlobInputStreamAssetDataSource p_lockForOpening], POSBlobInputStreamAssetDataSource.m:266
2014-12-09 13:58:18.060 HelloWorld[1634:631286] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: ![[NSThread currentThread] isMainThread]'
*** First throw call stack:
(0x22d8749f 0x3053dc8b 0x22d87375 0x23a58d7f 0x299e5 0x28ddb 0x284d7 0x6c6e1 0x794b5 0x23a97d6f 0x22d4dd57 0x22d4d167 0x22d4b7cd 0x22c993c1 0x22c991d3 0x2a0970a9 0x262a8fa1 0x26a13 0x30abdaaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by pronebird** [comment]
To be honest, I have tried another solution and with a simple patch I was able to make it work:

https://github.com/pronebird/FMAssetStream/blob/patch-1/Pod/Classes/FMAssetInputStream.m

Yes it does not handle errors yet, but it works perfectly fine with AFNetworking, and AFN calls `read:maxLength:` on background thread so I don't have problem with main thread being busy reading files etc...

Once again I am not much familiar with all the perils of NSStream subclassing, and I read a lot of weird stuff about CFNetwork calling private methods, etc..
